name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./clover.xml,./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
